model : # xgboost' 'logistic_regression' 'tabnet' 'ft_transformer' 'category_embedding' 'gandalf'
  - 'xgboost'

# Preprocessing settings
impute_strategy : 'mean'
missing_threshold : 0.7
remove_out_layers : False
scaling_mode : 'normalization'

# Training LDGD
load_trained_model : False
batch_size : 100
num_epochs : 100
test_size: 0.2

# Enable or disable debug mode
debug_mode: false


sampling_method: # 'RandomOverSampler' 'RandomUnderSampler' 'SMOTE' 'None'
  - 'SMOTE'


