# Dataset name to use : "pilot01" "clear"
dataset: "pet_ct"

model: "unet"

metric_list:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"

# Training LDGD
load_trained_model : False
batch_size : 100
num_epochs : 100
test_size: 0.2

# Load a pretrained saved_model
load_pretrained_model: true

# Enable or disable debug mode
debug_mode: false

